//localhost:3000/api/contacts
###Get all contacts
GET https://contacts-21ut.onrender.com/contacts

###Get contact by ID
GET https://contacts-21ut.onrender.com/contacts/68c33a55f7c119affe28e912
###Create a new contact
POST https://contacts-21ut.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Smith",
    "lastName": "Joseph",
    "email": "smith.joseph@example.com",
    "favoriteColor": "white",
    "birthday": "1982-02-02"

}
###Update a contact by ID
PUT https://contacts-21ut.onrender.com/contacts/68c33a55f7c119affe28e912
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane@example.com",
    "favoriteColor": "Blue",
    "birthday": "1992-02-02"
}
###Delete a contact by ID
DELETE https://contacts-21ut.onrender.com/contacts/68c33832f7c119affe28e911
